encoding: utf-8


title: Flyg0n Blog
description: Flyg0n Blog
keywords: Flyg0n,Blog,C++,Cyber Security,Linux
author: Flyg0n
language: en
footerText: 'Flyg0n - The personal blog of Sang P.Q - Build with Jekyll'

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']

domainUrl: ''
baseurl: ''

menu:
  - title: home
    url: /
  - title: catagorize
    url: /pages/categories.html
  - title: search
    url: /pages/search.html
    # title: 
    # url: /pages/links.html
  # - title: 留言
  #  url: /pages/chat.html
  - title: about
    url: /pages/about.html

extClickEffect: true

extAdsense: false

extMTA: true

extBaidu: false

extMath: false


    
